// Mandate 2.0 — People (volunteers & supporters) data
//
// The module reads live records via useLiveRecords('people','volunteer',
// VOLUNTEERS). Real volunteers arrive through the public intake form, admin
// entry, or CSV import; the records below are synthetic but realistic sample
// data (fictional BC riding "Meridian West") used to seed a demo workspace.
// The dossier renders straight from the people.volunteer schema, so every
// array-typed field is an array and statuses use the schema's enum values.
const VOLUNTEERS = [
  {
    id: 'VOL-001',
    first: 'Harpreet', last: 'Gill',
    addr: '341 Maple Crescent', city: 'Surrey', postal: 'V3R 2K8',
    phone: '604-555-0101', cell: '604-555-0102',
    email1: 'harpreet.gill@example.ca', email2: '',
    instagram: '@harpreet.builds',
    dob: '1990-03-14', citizenship: 'Canadian', riding: 'Meridian West',
    languages: ['English', 'Punjabi', 'Hindi'], preferredLanguage: 'English',
    availabilityOnline: 'Weeknights — 7pm–9pm; available', availabilityInPerson: 'Sat — 10am–4pm',
    politicalExperience: ['Canvassing', 'Scrutineer'],
    wantsToRun: false, contactEvents: true, contactVolunteer: true,
    workExperience: ['Management', 'Retail'],
    firstAid: true, firstAidLevel: 'OFA Level 1',
    preferredRoles: ['Door knocking/canvassing', 'Lawn sign installation'],
    skills: ['Public speaking', 'Customer service', 'Lift 50 lbs'],
    interestedFreeEvents: true, freeEvents: ['Potluck dinners', 'Hiking'],
    emergencyName: 'Manjit Gill', emergencyPhone: '604-555-0103',
    referral: 'Riding association',
    holidays: ['Vaisakhi', 'Diwali', 'Canada Day'],
    motivation: 'Want better housing options for young families in the riding.',
    topIssues: ['Lowering housing costs', 'Strengthening the economy'],
    hasResume: true,
    status: 'active', source: 'public form', tags: ['team-lead', 'reliable'],
    notes: 'Strong canvass captain; happy to lead Saturday turf.',
  },
  {
    id: 'VOL-002',
    first: 'Emily', last: 'Chen',
    addr: '88 Riverside Dr', city: 'Burnaby', postal: 'V5H 4M2',
    cell: '778-555-0204', email1: 'emily.chen@example.ca',
    twitter: '@emchen',
    dob: '1997-08-22', citizenship: 'Canadian', riding: 'Meridian West',
    languages: ['English', 'Cantonese', 'Mandarin'], preferredLanguage: 'English',
    availabilityOnline: 'Flexible — remote phone banking any evening',
    politicalExperience: ['Fundraising'],
    wantsToRun: true, contactEvents: true, contactVolunteer: true,
    workExperience: ['Social media', 'Influencer'],
    preferredRoles: ['Social media management', 'Written content/technical writing'],
    skills: ['Writing', 'Research', 'Excel'],
    interestedPaidEvents: true, paidEvents: ['Wine tasting', 'Theatre'],
    emergencyName: 'David Chen', emergencyPhone: '778-555-0205',
    referral: 'Friend',
    holidays: ['Chinese New Year', "New Year's Day"],
    motivation: 'Believe young people need a real seat at the table.',
    topIssues: ['Youth prosperity', 'Democracy', 'Protecting the environment'],
    hasResume: true, resumeUrl: 'https://example.ca/resume/echen',
    status: 'active', source: 'event', tags: ['comms', 'future-candidate'],
    notes: 'Interested in running locally in a future cycle.',
  },
  {
    id: 'VOL-003',
    first: 'Robert', last: 'MacDonald',
    addr: '12 Birchwood Ave', city: 'New Westminster', postal: 'V3L 1A9',
    phone: '604-555-0307', email1: 'r.macdonald@example.ca',
    dob: '1958-01-09', citizenship: 'Canadian', riding: 'Meridian West',
    languages: ['English'], preferredLanguage: 'English',
    availabilityInPerson: 'Weekday mornings',
    politicalExperience: ['Campaign manager', 'Party executive'],
    wantsToRun: false, contactEvents: true, contactVolunteer: true,
    workExperience: ['Executive management', 'Professional driver'],
    preferredRoles: ['Carpool driving', 'General volunteer'],
    skills: ['Negotiating', 'Coaching'],
    emergencyName: 'Susan MacDonald', emergencyPhone: '604-555-0308',
    referral: 'Long-time member',
    holidays: ['Christmas', 'Canada Day'],
    motivation: 'Decades of organizing experience I want to put to use.',
    topIssues: ['Anti-corruption / organized crime', 'Improving healthcare'],
    status: 'active', source: 'import', tags: ['driver', 'mentor'],
    notes: 'Available to drive GOTV on election day.',
  },
  {
    id: 'VOL-004',
    first: 'Fatima', last: 'Ali',
    addr: '506 Cedar Flats Rd', city: 'Coquitlam', postal: 'V3K 6T1',
    cell: '778-555-0410', email1: 'fatima.ali@example.ca',
    dob: '1985-11-30', citizenship: 'Permanent resident', riding: 'Meridian West',
    languages: ['English', 'Arabic'], preferredLanguage: 'Arabic',
    childcareHours: 'Weekday evenings, Sat mornings', wantsFreeChildcare: true,
    availabilityOnline: 'After 8pm once kids are down',
    politicalExperience: [],
    wantsToRun: false, contactEvents: true, contactVolunteer: true,
    workExperience: ['Child care', 'Teacher'],
    preferredRoles: ['Child minding', 'Outreach'],
    skills: ['Motivating', 'Public speaking'],
    emergencyName: 'Omar Ali', emergencyPhone: '778-555-0411',
    referral: 'Community centre',
    holidays: ['Eid al-Fitr', 'Eid al-Adha', 'Ramadan'],
    motivation: 'Want my community to feel represented.',
    topIssues: ['Lowering housing costs', 'Improving healthcare', 'Reforming education'],
    status: 'prospect', source: 'public form', tags: ['outreach', 'newcomer-liaison'],
    notes: 'Needs childcare to attend in-person shifts.',
  },
  {
    id: 'VOL-005',
    first: 'Tyler', last: 'Nguyen',
    city: 'Surrey', postal: 'V3S 0P4',
    cell: '604-555-0512', email1: 'tyler.nguyen@example.ca',
    twitter: '@tylern_codes',
    dob: '2002-05-17', citizenship: 'Canadian', riding: 'Meridian West',
    languages: ['English'], preferredLanguage: 'English',
    languagesOther: 'Vietnamese',
    availabilityOnline: 'Most evenings; weekends flexible',
    politicalExperience: [],
    wantsToRun: false, contactEvents: true, contactVolunteer: true,
    workExperience: ['Computer programming', 'Network/computer'],
    preferredRoles: ['Computer technology', 'Computer/data security', 'Data entry'],
    skills: ['Excel', 'Typing 60 wpm', 'Research'],
    interestedFreeEvents: true, freeEvents: ['Video games', 'Board games'],
    emergencyName: 'Linh Nguyen', emergencyPhone: '604-555-0513',
    referral: 'University club',
    holidays: ["New Year's Day", 'Chinese New Year'],
    motivation: 'Tech skills should help campaigns run better.',
    topIssues: ['Youth prosperity', 'Democracy'],
    status: 'prospect', source: 'public form', tags: ['tech', 'student'],
    notes: 'Offered to help build the volunteer database.',
  },
  {
    id: 'VOL-006',
    first: 'Grace', last: 'Okonkwo',
    addr: '77 Willow Court', city: 'Burnaby', postal: 'V5C 3B2',
    cell: '778-555-0614', email1: 'grace.okonkwo@example.ca',
    dob: '1979-09-02', citizenship: 'Canadian', riding: 'Meridian West',
    languages: ['English', 'French'], preferredLanguage: 'English',
    availabilityInPerson: 'Weekends — all day',
    politicalExperience: ['Event planning/management'],
    wantsToRun: false, contactEvents: true, contactVolunteer: true,
    workExperience: ['Event planning/management', 'Non-profit'],
    firstAid: true, firstAidLevel: 'Standard First Aid',
    certifications: ['Food safe'],
    preferredRoles: ['Event management', 'Food service', 'Health and safety'],
    skills: ['Event management', 'Account management'],
    emergencyName: 'Chidi Okonkwo', emergencyPhone: '778-555-0615',
    referral: 'Volunteer fair',
    holidays: ['Christmas', 'Easter'],
    motivation: 'Good events build real community momentum.',
    topIssues: ['Strengthening the economy', 'Disability rights & inclusion'],
    status: 'active', source: 'event', tags: ['events', 'food-safe'],
    notes: 'Can run the volunteer appreciation night.',
  },
  {
    id: 'VOL-007',
    first: 'Daniel', last: 'Lefebvre',
    city: 'New Westminster', postal: 'V3M 5R8',
    cell: '604-555-0716', email1: 'daniel.lefebvre@example.ca',
    dob: '1968-12-12', citizenship: 'Canadian', riding: 'Meridian West',
    languages: ['English', 'French'], preferredLanguage: 'French',
    politicalExperience: ['Canvassing'],
    wantsToRun: false, contactEvents: false, contactVolunteer: false,
    workExperience: ['Sales'],
    preferredRoles: ['Telemarketing', 'General volunteer'],
    skills: ['Telemarketing', 'Sales'],
    referral: 'Newspaper ad',
    motivation: 'Used to canvass years ago; thinking about it again.',
    topIssues: ['Lowering taxes', 'Crime'],
    status: 'inactive', source: 'import', tags: ['lapsed'],
    notes: 'Volunteered last cycle; has not responded recently.',
  },
  {
    id: 'VOL-008',
    first: 'Sofia', last: 'Reyes',
    city: 'Coquitlam', postal: 'V3B 7N4',
    cell: '778-555-0818', email1: 'sofia.reyes@example.ca',
    instagram: '@sofiacreates',
    dob: '1994-06-28', citizenship: 'Canadian', riding: 'Meridian West',
    languages: ['English', 'Spanish'], preferredLanguage: 'English',
    availabilityOnline: 'Daytime, remote',
    politicalExperience: [],
    wantsToRun: false, contactEvents: true, contactVolunteer: true,
    workExperience: ['Advertising', 'Brand management', 'Audio/video'],
    preferredRoles: ['Video production', 'Camera person', 'Social media management'],
    skills: ['PowerPoint', 'Writing'],
    disability: 'Mobility — uses a wheelchair',
    accommodation: 'Step-free venues and a seated role',
    interestedFreeEvents: true, freeEvents: ['Karaoke', 'Picnics'],
    emergencyName: 'Carlos Reyes', emergencyPhone: '778-555-0819',
    referral: 'Social media',
    holidays: ['Christmas', "New Year's Day"],
    motivation: 'Great storytelling can change minds.',
    topIssues: ['Disability rights & inclusion', 'Protecting the environment', 'Democracy'],
    hasResume: true,
    status: 'declined', source: 'public form', tags: ['creative', 'remote-only'],
    notes: 'Declined this cycle but open to remote content work later.',
  },
];

export { VOLUNTEERS };
